# Generated by Django 4.2.1 on 2023-06-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_recipe_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
    ]
