# Generated by Django 3.2.19 on 2023-06-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_colour_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название ингредиента'),
        ),
    ]
