# Generated by Django 4.2.1 on 2023-05-31 21:39

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_suscription_suscription_unique_user_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[users.validators.validate_username],
                verbose_name="Имя пользователя",
            ),
        ),
    ]
