# Generated by Django 4.2.1 on 2023-06-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Suscription",
            new_name="Subscription",
        ),
    ]
